// GET ACTIONS
export const GET_ALL_ROOMS = "GET_ALL_ROOMS";
export const ROOM_SUBSCRIPTION ="ROOM_SUBSCRIPTION";

// POST ACTIONS
export const POST_MESSAGE = "POST_MESSAGE";
export const CREATE_ROOM = "CREATE_ROOM";

// AUTH ACTIONS
export const ASSIGN_USER = "ASSIGN_USER";
export const ASSIGN_ROOM_ID = "ASSIGN_ROOM_ID";